### PR TITLE
Log user out of app when credentials expire

### LINKED ISSUE #209: Log user out of app when credentials expire
During pilot testing, technicians noticed `Loading...` appear forever in the New Work Order form Signals field. We realized that logging out/in resolved this issue (since the API requests were failing (403) in the background due to expired credentials). 

Need to redirect the user to the login screen if their credentials are expired so that they are forced to log back in.

### PR DESCRIPTION
**Pull request by mddilley**
Closes #209

### CODE REVIEW

**Comment by mddilley** [comment]
This PR changes the logic for checking if a user is logged in or not. The new check relies on the existing condition of a `knackUserToken` cookie being present but also adds another timestamp cookie, `knackUserTokenExpiration`, to track user token expiration. 

Also, the `BrowserRouter` and `Switch` wrappers were removed from `App.js` and replaced with `withRouter` in order to access the `location` prop to determine when the route changes. The route change was used as a hook to check if the user is still logged in or not. If they are not logged in, a piece of boolean state is switched to render a redirect to the login page.

This feature was tested by editing the `knackUserTokenExpiration` in browser to expire and attempting to navigate the app.

File: src/components/App.js [hunk 1]
```diff
@@ -70,13 +65,22 @@ class App extends Component {
...
     };
   }
 
   setKnackUserToken = token => {
     // Set cookie first to prevent API call in UserInfo from failing to auth
+    // Set additional expiration cookie to timestamp token creation
+    Cookies.set(
+      "knackUserTokenExpiration",
+      moment()
+        .add(2, "days")
```
Comment (mateoclarke) [inline src/components/App.js]: I ❤️ moment for this type of thing.

**Comment by mateoclarke** [comment]
As we discussed on Slack, I caught some bugs with how this works so consider my "approval" premature but its on the right track.
